doctrine_migrations:
    migrations_paths:
        'App\Events\Migrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'
    storage:
        table_storage:
            table_name: 'migration_versions'
