
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Somnambulist\Components\ReadModels\EventSubscribers\IdentityMapClearerSubscriber:
        tags: ['kernel.event_subscriber']

    Somnambulist\Domain\Events\Publishers\DoctrineEventPublisher:
        tags: ['doctrine.event_subscriber']

    Somnambulist\Domain\Events\Adapters\MessengerSerializer:

    somnambulist.domain.event_serializer:
        alias: Somnambulist\Domain\Events\Adapters\MessengerSerializer

    Somnambulist\Domain\Commands\CommandBus:
        alias: Somnambulist\Domain\Commands\Adapters\MessengerCommandBus
        public: true

    Somnambulist\Domain\Commands\Adapters\MessengerCommandBus:

    Somnambulist\Domain\Events\EventBus:
        alias: Somnambulist\Domain\Events\Adapters\MessengerEventBus
        public: true

    Somnambulist\Domain\Events\Adapters\MessengerEventBus:

    Somnambulist\Domain\Queries\QueryBus:
        alias: Somnambulist\Domain\Queries\Adapters\MessengerQueryBus
        public: true

    Somnambulist\Domain\Queries\Adapters\MessengerQueryBus:

    Somnambulist\ApiBundle\ArgumentResolvers\:
        resource: '../../vendor/somnambulist/api-bundle/src/ArgumentResolvers/'
        tags:
            - { name: controller.argument_value_resolver, priority: 105 }

    Somnambulist\Components\ReadModels\TypeCasters\DoctrineTypeCaster:
        tags: ['somnambulist.read_models.type_caster']
