version: '3.5'

services:
  events-app:
    build:
      context: .
      dockerfile: config/docker/test/app/Dockerfile
    depends_on:
      - postgres
    networks:
      - backend

  events-redis:
    image: redis:alpine
    networks:
      - backend

  db-events:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: mycompany
      POSTGRES_PASSWORD: secret
    volumes:
      - ./config/docker/test/postgres:/docker-entrypoint-initdb.d
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmqcookienamehere
    networks:
      - backend

networks:
  backend:
    driver: bridge
